export const config = { runtime: 'edge' };

import { makeEtag, serveStatic } from '../../server/_shared/v8-static';

// Source: https://github.com/koala73/worldmonitor/blob/main/shared/geo-data.ts (INTEL_HOTSPOTS)
// Already synced with upstream (29/29) — nothing to pull in for now.


export interface HotspotHistory {
  lastMajorEvent: string;
  lastMajorEventDate: string; // "YYYY-MM-DD"
  precedentDescription: string;
  cyclicalRisk: string;
}

export interface IntelHotspot {
  id: string;
  name: string;
  subtext: string;
  lat: number;
  lon: number;
  description: string | null;
  agencies: string[];
  escalationScore: number | null;
  escalationTrend: string | null;
  escalationIndicators: string[];
  history: HotspotHistory | null;
  whyItMatters: string | null;
}

const DATA: IntelHotspot[] = [
  {
    id: "sahel",
    name: "Sahel",
    subtext: "Insurgency/Coups",
    lat: 14.0,
    lon: -1.0,
    description:
      "Region of instability, military coups, and Islamist insurgency. Russian influence growing.",
    agencies: ["Wagner", "Junta Forces"],
    escalationScore: 4,
    escalationTrend: "escalating",
    escalationIndicators: [
      "4 coups since 2020",
      "French forces expelled",
      "Wagner/Africa Corps expansion",
      "ECOWAS sanctions",
    ],
    history: {
      lastMajorEvent: "Niger coup",
      lastMajorEventDate: "2023-07-26",
      precedentDescription: "4 military coups in 3 years (Mali 2020/2021, Burkina Faso 2022, Niger 2023)",
      cyclicalRisk: "Dry season offensives (Oct–May)",
    },
    whyItMatters:
      "Russian influence expanding in former French sphere; jihadist groups gaining territory; migration pressure on Europe",
  },
  {
    id: "haiti",
    name: "Port-au-Prince",
    subtext: "Haiti Crisis",
    lat: 18.5,
    lon: -72.3,
    description: "Gang violence, government collapse, international security mission.",
    agencies: ["UN", "HNP", "Kenya Police"],
    escalationScore: 4,
    escalationTrend: "stable",
    escalationIndicators: [
      "Gangs control 80% of capital",
      "PM resigned under pressure",
      "Kenya-led mission deployed",
      "Mass displacement",
    ],
    history: {
      lastMajorEvent: "PM Henry resignation",
      lastMajorEventDate: "2024-03-11",
      precedentDescription: "Repeated state collapse (2004 Aristide, 2021 Moïse assassination, 2024 gang takeover)",
      cyclicalRisk: "Hurricane season vulnerability (Jun–Nov)",
    },
    whyItMatters:
      "Humanitarian catastrophe at US doorstep; migration surge potential; test of African-led peacekeeping",
  },
  {
    id: "horn_africa",
    name: "Horn of Africa",
    subtext: "Piracy/Conflict",
    lat: 10.0,
    lon: 49.0,
    description: "Resurgent piracy, Al-Shabaab activity, Ethiopia-Somaliland port dispute.",
    agencies: ["USAFRICOM", "EUNAVFOR"],
    escalationScore: 4,
    escalationTrend: "escalating",
    escalationIndicators: [
      "Houthi attacks on shipping",
      "Somali piracy resurgence",
      "Ethiopia-Somaliland MoU dispute",
      "Sudan civil war spillover",
    ],
    history: {
      lastMajorEvent: "Sudan war outbreak",
      lastMajorEventDate: "2023-04-15",
      precedentDescription: "Ethiopia-Eritrea war, Tigray war, Somali civil war, Sudan coups, piracy waves",
      cyclicalRisk: "Monsoon affects naval operations (Jun–Sep)",
    },
    whyItMatters:
      "Bab el-Mandeb chokepoint security; 12% of global trade at risk; Red Sea shipping rerouting",
  },
  {
    id: "pak_afghan",
    name: "Pakistan–Afghanistan Border",
    subtext: "Border Conflict / TTP",
    lat: 31.8,
    lon: 69.0,
    description:
      "Ongoing conflict along the Pak–Afghan border. Pakistan military operations against TTP; cross-border strikes and border closures. Tensions with Afghan Taliban over border security.",
    agencies: ["Pakistan Military", "TTP", "Afghan Taliban"],
    escalationScore: 4,
    escalationTrend: "escalating",
    escalationIndicators: [
      "Border clashes and closures",
      "Pakistan airstrikes in Afghanistan",
      "TTP attacks in KP",
      "Torkham/Chaman crossing tensions",
    ],
    history: {
      lastMajorEvent: "Cross-border strikes and border closures",
      lastMajorEventDate: "2024-01-01",
      precedentDescription: "Recurring border crises, TTP resurgence post-2021, militant sanctuaries in Afghanistan",
      cyclicalRisk: "Militant infiltration; seasonal operations",
    },
    whyItMatters:
      "Nuclear-armed state at contested border; regional stability; displacement and humanitarian impact",
  },
  {
    id: "dc",
    name: "DC",
    subtext: "Pentagon Pizza Index",
    lat: 38.9,
    lon: -77.0,
    description: "US government and military headquarters. Intelligence community center.",
    agencies: ["Pentagon", "CIA", "NSA", "State Dept"],
    escalationScore: null,
    escalationTrend: null,
    escalationIndicators: [],
    history: null,
    whyItMatters: null,
  },
  {
    id: "silicon_valley",
    name: "Silicon Valley",
    subtext: "Tech/AI Hub",
    lat: 37.4,
    lon: -122.1,
    description: "Global tech center. AI development hub. Major economic indicator.",
    agencies: ["Big Tech", "AI Labs", "VC"],
    escalationScore: null,
    escalationTrend: null,
    escalationIndicators: [],
    history: null,
    whyItMatters: null,
  },
  {
    id: "wall_street",
    name: "Wall Street",
    subtext: "Financial Hub",
    lat: 40.7,
    lon: -74.0,
    description: "Global financial center. Market movements. Fed policy.",
    agencies: ["Fed", "SEC", "NYSE"],
    escalationScore: null,
    escalationTrend: null,
    escalationIndicators: [],
    history: null,
    whyItMatters: null,
  },
  {
    id: "houston",
    name: "Houston",
    subtext: "Energy/Space",
    lat: 29.76,
    lon: -95.37,
    description: "Energy sector HQ. NASA mission control. Space industry.",
    agencies: ["NASA", "Energy Corps"],
    escalationScore: null,
    escalationTrend: null,
    escalationIndicators: [],
    history: null,
    whyItMatters: null,
  },
  {
    id: "moscow",
    name: "Moscow",
    subtext: "Kremlin Activity",
    lat: 55.75,
    lon: 37.6,
    description: "Russian Federation command center. Military operations hub.",
    agencies: ["Kremlin", "FSB", "GRU", "SVR"],
    escalationScore: 4,
    escalationTrend: "stable",
    escalationIndicators: [
      "Ukraine war ongoing",
      "Mobilization potential",
      "Nuclear rhetoric",
      "Wagner aftermath",
    ],
    history: {
      lastMajorEvent: "Wagner mutiny",
      lastMajorEventDate: "2023-06-24",
      precedentDescription: "Crimea annexation 2014, Ukraine invasion 2022",
      cyclicalRisk: "Victory Day (May 9) speeches, Putin addresses",
    },
    whyItMatters: "Nuclear power at war; energy leverage over Europe; global order revisionism",
  },
  {
    id: "beijing",
    name: "Beijing",
    subtext: "PLA/MSS Activity",
    lat: 39.9,
    lon: 116.4,
    description: "Chinese Communist Party headquarters. PLA command center.",
    agencies: ["PLA", "MSS", "CCP Politburo"],
    escalationScore: 3,
    escalationTrend: "stable",
    escalationIndicators: [
      "Taiwan Strait exercises",
      "South China Sea militarization",
      "Tech decoupling",
      "Xi third term",
    ],
    history: {
      lastMajorEvent: "Xi unprecedented third term",
      lastMajorEventDate: "2022-10-22",
      precedentDescription: "Tiananmen 1989, Hong Kong crackdown 2020, COVID lockdowns 2022",
      cyclicalRisk: "Party Congress (every 5 years), Tiananmen anniversary (June 4)",
    },
    whyItMatters: "Largest economy by PPP; primary US strategic competitor; Taiwan contingency risk",
  },
  {
    id: "kyiv",
    name: "Kyiv",
    subtext: "Conflict Zone",
    lat: 50.45,
    lon: 30.5,
    description: "Active conflict zone. NATO support operations.",
    agencies: ["Ukrainian Armed Forces", "SBU"],
    escalationScore: 5,
    escalationTrend: "stable",
    escalationIndicators: [
      "Active combat operations",
      "Western weapons deliveries",
      "Drone warfare escalation",
      "Nuclear plant risks",
    ],
    history: {
      lastMajorEvent: "Russian full invasion",
      lastMajorEventDate: "2022-02-24",
      precedentDescription: "Crimea annexation 2014, Donbas war 2014–2022",
      cyclicalRisk: "Spring/summer offensive season, Winter energy attacks",
    },
    whyItMatters: "Largest European war since WWII; NATO Article 5 test; global food/energy security",
  },
  {
    id: "taipei",
    name: "Taipei",
    subtext: "Strait Watch",
    lat: 25.03,
    lon: 121.5,
    description: "Taiwan Strait tensions. Semiconductor supply chain.",
    agencies: ["ROC Military", "TSMC"],
    escalationScore: 3,
    escalationTrend: "stable",
    escalationIndicators: [
      "PLA exercises around Taiwan",
      "US arms sales",
      "TSMC Arizona fab",
      "DPP governance",
    ],
    history: {
      lastMajorEvent: "Pelosi Taiwan visit",
      lastMajorEventDate: "2022-08-02",
      precedentDescription: "1954–55 Strait Crisis, 1995–96 missile crisis, 2022 exercises",
      cyclicalRisk: "US-Taiwan political visits, PRC National Day (Oct 1)",
    },
    whyItMatters:
      "TSMC produces 90% of advanced chips; conflict would devastate global tech supply chains",
  },
  {
    id: "tehran",
    name: "Tehran",
    subtext: "IRGC Activity",
    lat: 35.7,
    lon: 51.4,
    description: "Iranian nuclear program. Regional proxy operations.",
    agencies: ["IRGC", "Quds Force", "MOIS"],
    escalationScore: 4,
    escalationTrend: "escalating",
    escalationIndicators: [
      "Near-weapons-grade enrichment",
      "Proxy attacks on Israel",
      "Houthi coordination",
      "Succession uncertainty",
    ],
    history: {
      lastMajorEvent: "JCPOA collapse acceleration",
      lastMajorEventDate: "2023-01-01",
      precedentDescription: "Revolution 1979, Iran-Iraq War, JCPOA negotiations, Soleimani assassination",
      cyclicalRisk: "Quds Day (annually), Khamenei health status",
    },
    whyItMatters: "Near-nuclear threshold state; controls Strait of Hormuz; Axis of Resistance coordinator",
  },
  {
    id: "telaviv",
    name: "Tel Aviv",
    subtext: "Mossad/IDF",
    lat: 32.1,
    lon: 34.8,
    description: "Military operations. Regional security. Intelligence activities.",
    agencies: ["IDF", "Mossad", "Shin Bet"],
    escalationScore: 5,
    escalationTrend: "stable",
    escalationIndicators: [
      "Gaza operations ongoing",
      "Hezbollah northern front",
      "Iran shadow war",
      "Judicial crisis paused",
    ],
    history: {
      lastMajorEvent: "October 7 attacks",
      lastMajorEventDate: "2023-10-07",
      precedentDescription: "1948 War, 1967 Six-Day War, 1973 Yom Kippur, Lebanon 2006, Gaza wars",
      cyclicalRisk: "Jewish holidays, Ramadan tensions, election cycles",
    },
    whyItMatters:
      "Regional escalation risk to multi-front war; US treaty ally; Iran confrontation flashpoint",
  },
  {
    id: "pyongyang",
    name: "Pyongyang",
    subtext: "DPRK Watch",
    lat: 39.0,
    lon: 125.75,
    description: "Nuclear weapons program. Missile testing. Cyber operations.",
    agencies: ["KPA", "RGB", "Lazarus Group"],
    escalationScore: 3,
    escalationTrend: "stable",
    escalationIndicators: [
      "ICBM testing resumed",
      "Russia arms cooperation",
      "Satellite launches",
      "Constitution change on ROK",
    ],
    history: {
      lastMajorEvent: "Hwasong-18 ICBM test",
      lastMajorEventDate: "2023-12-18",
      precedentDescription: "Korean War 1950–53, nuclear tests 2006–2017, Trump summits, missile tests ongoing",
      cyclicalRisk: "Kim Il-sung birthday (April 15), party anniversaries",
    },
    whyItMatters:
      "Nuclear-armed hermit state; ICBM can reach US mainland; cyber threat actor; Russia military supplier",
  },
  {
    id: "london",
    name: "London",
    subtext: "GCHQ/MI6",
    lat: 51.5,
    lon: -0.12,
    description: "UK intelligence headquarters. Five Eyes member.",
    agencies: ["MI6", "GCHQ", "MI5"],
    escalationScore: null,
    escalationTrend: null,
    escalationIndicators: [],
    history: null,
    whyItMatters: null,
  },
  {
    id: "brussels",
    name: "Brussels",
    subtext: "NATO HQ",
    lat: 50.85,
    lon: 4.35,
    description: "NATO alliance headquarters. European Union center.",
    agencies: ["NATO", "EU Commission"],
    escalationScore: null,
    escalationTrend: null,
    escalationIndicators: [],
    history: null,
    whyItMatters: null,
  },
  {
    id: "caracas",
    name: "Caracas",
    subtext: "Venezuela Crisis",
    lat: 10.5,
    lon: -66.9,
    description: "Political crisis. Economic sanctions. Regional instability.",
    agencies: ["Maduro Govt", "SEBIN"],
    escalationScore: null,
    escalationTrend: null,
    escalationIndicators: [],
    history: null,
    whyItMatters: null,
  },
  {
    id: "mexico",
    name: "Mexico City",
    subtext: "Cartel Violence",
    lat: 23.6,
    lon: -102.5,
    description:
      "Cartel warfare, fentanyl trafficking, military deployments, state fragility in multiple regions.",
    agencies: ["Sedena", "National Guard", "DEA", "FGR"],
    escalationScore: 4,
    escalationTrend: "escalating",
    escalationIndicators: [
      "Sinaloa cartel fragmentation",
      "CJNG territorial expansion",
      "Military deployed to multiple states",
      "Record fentanyl seizures",
      "Prison breaks and gang violence",
    ],
    history: {
      lastMajorEvent: "Sinaloa cartel leadership crisis",
      lastMajorEventDate: "2024-07-25",
      precedentDescription:
        "Decades of cartel wars (Sinaloa vs CJNG, Zetas era, Calderón drug war 2006, El Chapo captures)",
      cyclicalRisk: "Election cycles trigger violence; cartel leadership changes spark turf wars",
    },
    whyItMatters:
      "Largest US land border; fentanyl crisis killing 100k+ Americans/year; regional destabilization; migration driver",
  },
  {
    id: "nuuk",
    name: "Nuuk",
    subtext: "Greenland Intel",
    lat: 64.18,
    lon: -51.7,
    description: "Arctic strategic territory. US military presence, sovereignty questions.",
    agencies: ["Danish Defence", "US Space Force", "Arctic Council"],
    escalationScore: null,
    escalationTrend: null,
    escalationIndicators: [],
    history: null,
    whyItMatters: null,
  },
  {
    id: "riyadh",
    name: "Riyadh",
    subtext: "Saudi GIP/MBS",
    lat: 24.7,
    lon: 46.7,
    description: "Saudi Arabia power center. OPEC+ decisions. Regional influence.",
    agencies: ["GIP", "Saudi Royal Court", "Aramco"],
    escalationScore: null,
    escalationTrend: null,
    escalationIndicators: [],
    history: null,
    whyItMatters: null,
  },
  {
    id: "cairo",
    name: "Cairo",
    subtext: "Egypt/GIS",
    lat: 30.0,
    lon: 31.2,
    description: "Egyptian command. Gaza border control. Suez Canal security.",
    agencies: ["GIS", "Egyptian Armed Forces"],
    escalationScore: null,
    escalationTrend: null,
    escalationIndicators: [],
    history: null,
    whyItMatters: null,
  },
  {
    id: "baghdad",
    name: "Baghdad",
    subtext: "Iraq/PMF",
    lat: 33.3,
    lon: 44.4,
    description: "Iraqi government. Iran-backed militias. US military presence.",
    agencies: ["Iraqi Security Forces", "PMF", "US Embassy"],
    escalationScore: null,
    escalationTrend: null,
    escalationIndicators: [],
    history: null,
    whyItMatters: null,
  },
  {
    id: "damascus",
    name: "Damascus",
    subtext: "Syria Crisis",
    lat: 33.5,
    lon: 36.3,
    description: "Syrian civil war aftermath. Multiple foreign interventions.",
    agencies: ["Syrian Govt", "HTS", "Russian Forces", "Turkish Forces"],
    escalationScore: null,
    escalationTrend: null,
    escalationIndicators: [],
    history: null,
    whyItMatters: null,
  },
  {
    id: "doha",
    name: "Doha",
    subtext: "Qatar/Al Udeid",
    lat: 25.3,
    lon: 51.5,
    description: "Qatar diplomatic hub. US CENTCOM base. Al Jazeera HQ.",
    agencies: ["Qatari State Security", "CENTCOM Forward HQ"],
    escalationScore: null,
    escalationTrend: null,
    escalationIndicators: [],
    history: null,
    whyItMatters: null,
  },
  {
    id: "ankara",
    name: "Ankara",
    subtext: "Turkey/MIT",
    lat: 39.9,
    lon: 32.9,
    description: "NATO member. Kurdish conflict. Syria/Libya operations.",
    agencies: ["MIT", "Turkish Armed Forces", "AKP"],
    escalationScore: null,
    escalationTrend: null,
    escalationIndicators: [],
    history: null,
    whyItMatters: null,
  },
  {
    id: "beirut",
    name: "Beirut",
    subtext: "Lebanon/Hezbollah",
    lat: 33.9,
    lon: 35.5,
    description: "Lebanon crisis. Hezbollah stronghold. Israel border tensions.",
    agencies: ["LAF", "Hezbollah", "UNIFIL"],
    escalationScore: null,
    escalationTrend: null,
    escalationIndicators: [],
    history: null,
    whyItMatters: null,
  },
  {
    id: "sanaa",
    name: "Sana'a",
    subtext: "Yemen/Houthis",
    lat: 15.4,
    lon: 44.2,
    description: "Yemen conflict. Houthi Red Sea attacks. Shipping disruption.",
    agencies: ["Houthi Forces", "Saudi Coalition", "US Navy"],
    escalationScore: 4,
    escalationTrend: "escalating",
    escalationIndicators: [
      "Red Sea shipping attacks",
      "US/UK strikes on Yemen",
      "Iran weapon supplies",
      "Commercial ship seizures",
    ],
    history: {
      lastMajorEvent: "Red Sea campaign begins",
      lastMajorEventDate: "2023-11-19",
      precedentDescription: "Civil war since 2014, Saudi intervention 2015, US strikes 2024",
      cyclicalRisk: "Ramadan, Gaza war linkage",
    },
    whyItMatters:
      "Disrupting 12% of global trade via Suez; insurance costs spiking; Iran proxy demonstration",
  },
  {
    id: "abudhabi",
    name: "Abu Dhabi",
    subtext: "UAE/ECSR",
    lat: 24.5,
    lon: 54.4,
    description: "UAE strategic hub. Regional military operations.",
    agencies: ["ECSR", "UAE Armed Forces"],
    escalationScore: null,
    escalationTrend: null,
    escalationIndicators: [],
    history: null,
    whyItMatters: null,
  },
];

const ETAG = makeEtag(DATA);

export default function handler(req: Request): Promise<Response> {
  return serveStatic(req, DATA, ETAG);
}
